spring.application.name=notifications

server.port=8082


# Importar secretos JWT
spring.config.import=optional:file:./secrets.properties

# ---- API KEY Resend ----
resend.api.key=${RESEND_API_KEY}
resend.mail.from=Mariluz <onboarding@resend.dev>
