spring.application.name=notifications

server.port=8089


# Importar secretos JWT
spring.config.import=optional:file:./secrets.properties

# ---- API KEY Resend ----
resend.api.key=${RESEND_API_KEY}
resend.mail.from=Mariluz <onboarding@resend.dev>

# SWAGGER OPEN API.
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
