spring.application.name=notifications-service

server.port=8089


# Importar secretos JWT
spring.config.import=optional:file:./secrets.properties

# ---- API KEY Resend ----
resend.api.key=${RESEND_API_KEY}
resend.mail.from=Mariluz <onboarding@resend.dev>

# SWAGGER OPEN API.
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ---- REGISTRO EUREKA ----
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
